# Generated by Django 4.1.1 on 2022-09-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
